steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/api-depresion', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/api-depresion' ]

  # (Opcional) Despliegue automático en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        'api-depresion',
        '--image',
        'gcr.io/$PROJECT_ID/api-depresion',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--port',
        '8080'
      ]

images:
  - gcr.io/$PROJECT_ID/api-depresion
